GET {{hostname}}/health

###

POST {{hostname}}/api/users/signup
Content-Type: application/json

{
    "firstname": "Habeeb",
    "lastname": "Ashiru",
    "username": "bebo1",
    "email": "gmail.com@ashiruhabeeb",
    "password": "fit?Kam567",
    "confirmpassword": "fit?Kam567",
    "phone": "+2347061056780"
}

###

GET {{hostname}}/api/users/allrecords
Content-Type: application/json

###
GET {{hostname}}/api/users/fetch/username?username=bebo1
Content-Type: application/json

###
GET {{hostname}}/api/users/fetch/email?email=gmail.com@ashiruhabeeb
Content-Type: application/json

###
GET {{hostname}}/api/users/"e7be6f8d-8ba4-4e99-8959-f994434bd410"
Content-Type: application/json