GET {{hostname}}/health

###

POST {{hostname}}/api/users/signup
Content-Type: application/json

{
    "firstname": "Habeeb",
    "lastname": "Ashiru",
    "username": "bebo1",
    "email": "gmail.com@ashiruhabeeb",
    "password": "fit?Kam567",
    "confirmpassword": "fit?Kam567",
    "phone": "+2347061056780"
}

###

GET {{hostname}}/api/v1/allrecords
Content-Type: application/json

###
GET {{hostname}}/api/v1/get/bebo1
Content-Type: application/json

###
GET {{hostname}}/api/v1/fetch/gmail.com@ashiruhabeeb
Content-Type: application/json

###
GET {{hostname}}/api/v1/user/62feabae-ee47-4127-bb90-42888a4b2c54
Content-Type: application/json