GET {{hostname}}/health

###

POST {{hostname}}/api/v1/signup
Content-Type: application/json

{
    "firstname": "Selim",
    "lastname": "Bella",
    "username": "sBella",
    "email": "selim@yahoo.com",
    "password": "fitK@am!567",
    "confirmpassword": "fitK@am!567",
    "phone": "+3247060956780"
}

###

PATCH {{hostname}}/api/v1/udt/c68f3016-1f08-4ad1-bbf5-1a9d613349c3
Content-Type: application/json

{
    "firstname": "Messi"
}

###

GET {{hostname}}/api/v1/allrecords
Content-Type: application/json

###
GET {{hostname}}/api/v1/get/Asia
Content-Type: application/json

###
GET {{hostname}}/api/v1/fetch/r64@yahoo.com
Content-Type: application/json

###
GET {{hostname}}/api/v1/user/b8b5127f-f7f2-4555-a001-ad0d078b0ed2
Content-Type: application/json

###

DELETE {{hostname}}/api/v1/del/42459ff9-f021-4fbf-9bfc-cd9686b77ef8
Content-Type: application/json