# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - go run cmd/main.go
    silent: true

  apptidy:
    cmds:
      - go mod tidy
    silent: true

  devup:
    cmds:
      - docker compose up
    silent: true
